// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrEdJ-Fr1lrS9_-9Cs1Jmlzh8VlXIxTo',
    appId: '1:427500456148:web:c9170395cc6d1203ae5341',
    messagingSenderId: '427500456148',
    projectId: 'kitabantu-e5076',
    authDomain: 'kitabantu-e5076.firebaseapp.com',
    storageBucket: 'kitabantu-e5076.appspot.com',
    measurementId: 'G-9KVL0ZKPN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOgnB_pkUpP0d9_DeCBRk5ecmLgYnN6VU',
    appId: '1:427500456148:android:8539eee2a21e0b6eae5341',
    messagingSenderId: '427500456148',
    projectId: 'kitabantu-e5076',
    storageBucket: 'kitabantu-e5076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDBBUEf8XbTrOtR9pm7EkgK1cmxPoCPc',
    appId: '1:427500456148:ios:20dbfe858f64c247ae5341',
    messagingSenderId: '427500456148',
    projectId: 'kitabantu-e5076',
    storageBucket: 'kitabantu-e5076.appspot.com',
    iosBundleId: 'com.example.kitabantu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSDBBUEf8XbTrOtR9pm7EkgK1cmxPoCPc',
    appId: '1:427500456148:ios:20dbfe858f64c247ae5341',
    messagingSenderId: '427500456148',
    projectId: 'kitabantu-e5076',
    storageBucket: 'kitabantu-e5076.appspot.com',
    iosBundleId: 'com.example.kitabantu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrEdJ-Fr1lrS9_-9Cs1Jmlzh8VlXIxTo',
    appId: '1:427500456148:web:5c83b4e5f0447a6eae5341',
    messagingSenderId: '427500456148',
    projectId: 'kitabantu-e5076',
    authDomain: 'kitabantu-e5076.firebaseapp.com',
    storageBucket: 'kitabantu-e5076.appspot.com',
    measurementId: 'G-D1ZFCJSCGD',
  );
}
